"""Storage backend protocol."""

from typing import Protocol, runtime_checkable


@runtime_checkable
class StorageBackend(Protocol):
    async def upload_file(self, local_path: str, remote_key: str) -> bool: ...
    async def download_file(self, remote_key: str, local_path: str) -> bool: ...
    async def delete_file(self, remote_key: str) -> bool: ...
    async def file_exists(self, remote_key: str) -> bool: ...
    async def test_connection(self) -> dict: ...  # Returns {"ok": bool, "message": str}
